// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ErZ5_FHa5Cb-viat4F70q078zNOHWB4',
    appId: '1:59979582031:web:11a30fa736188325ab383a',
    messagingSenderId: '59979582031',
    projectId: 'homeautomated-b318b',
    authDomain: 'homeautomated-b318b.firebaseapp.com',
    storageBucket: 'homeautomated-b318b.appspot.com',
    measurementId: 'G-CLHS3WWBDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc8UhMJDDR3mQNfl4aeZfkEVPhNHOy-lY',
    appId: '1:59979582031:android:7df410ed0ffe7fe7ab383a',
    messagingSenderId: '59979582031',
    projectId: 'homeautomated-b318b',
    storageBucket: 'homeautomated-b318b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk_CspGpiFZ2J3LbIFZ13SUeJlLZT_iSU',
    appId: '1:59979582031:ios:729c89627e1eede8ab383a',
    messagingSenderId: '59979582031',
    projectId: 'homeautomated-b318b',
    storageBucket: 'homeautomated-b318b.appspot.com',
    iosBundleId: 'com.example.homeautomated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk_CspGpiFZ2J3LbIFZ13SUeJlLZT_iSU',
    appId: '1:59979582031:ios:729c89627e1eede8ab383a',
    messagingSenderId: '59979582031',
    projectId: 'homeautomated-b318b',
    storageBucket: 'homeautomated-b318b.appspot.com',
    iosBundleId: 'com.example.homeautomated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ErZ5_FHa5Cb-viat4F70q078zNOHWB4',
    appId: '1:59979582031:web:e17f59b4616c4e5aab383a',
    messagingSenderId: '59979582031',
    projectId: 'homeautomated-b318b',
    authDomain: 'homeautomated-b318b.firebaseapp.com',
    storageBucket: 'homeautomated-b318b.appspot.com',
    measurementId: 'G-QSF1BLPM0N',
  );
}
